### ISSUE TITLE
flash of unstyled content

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/create-choo-app#12]
Whenever you load the app there's a brief moment unstyled HTML is displayed. Was kinda surprised by this, given that we're bundling critical CSS in the head of the document already. Not sure how to fix this, but pretty sure we should (and can).

Ideas welcome!

**Comment by bcomnes** [comment]
` <link rel=“preload”> & <link rel=“prefetch”>`?

https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf

**Comment by yoshuawuyts** [comment]
Ah, yeah that explains it all! - Turns out CSS doesn't start painting until
all stylesheets have been loaded. Which kinda beats the point of what we
were going for. https://github.com/filamentgroup/loadCSS has a few neato
ideas we might steal, particularly:

<link rel="preload" href="path/to/mystylesheet.css" as="style"
onload="this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="path/to/mystylesheet.css"></noscript>
<script>/*! loadCSS. [c]2017 Filament Group, Inc. MIT License
*/(function(){ ... }());/*! loadCSS rel=preload polyfill. [c]2017
Filament Group, Inc. MIT License */(function(){ ... }());</script>


Gut feeling tells me their polyfill might not be as compact as it could be;
we should probs make this part of bankai hey (and like probably create an
HTML transform stream for this that solves it C: )

**Comment by yoshuawuyts** [comment]
Solved in latest bankai!
