### ISSUE TITLE
Service worker error after initializing

### ISSUE THREAD

**Issue by timwis** [choojs/create-choo-app#16]
After initializing a new create-choo-app and running `npm start`, the console shows an error

```
DOMException: Failed to register a ServiceWorker: The script does not have a MIME type.
```
 
<img width="696" alt="screen shot 2017-08-12 at 14 49 23" src="https://user-images.githubusercontent.com/761444/29243463-b10b39b6-7f6d-11e7-8342-d571dfd05212.png">

I assume this is a matter of bankai serving the wrong mime-type, but a google search yielded a [similar issue](https://github.com/jeffposnick/create-react-pwa/issues/11) in create-react-pwa that suggests you don't even want a SW on development mode anyway.

I've never used service workers before so I'm not sure what's wrong, but wanted to point this out in case it's not intentional.

**Comment by yoshuawuyts** [comment]
This still the case with new bankai?

**Comment by timwis** [comment]
![no](https://user-images.githubusercontent.com/761444/29250678-a507cf10-8014-11e7-99de-52b3b4760bd9.gif)
