### ISSUE TITLE
Error running on Node v6.11.0 

### ISSUE THREAD

**Issue by mcdonnelldean** [choojs/create-choo-app#21]
#  Steps
1. Install npx
2. Run `npx create-choo-app new-site`
3. Error is shown

## Error
```
$ npx create-choo-app new-site
npx: installed 29 in 5.648s
Creating a new Choo app in /Users/mcdonnelldean/repos/new-site.

Creating file package.json…

Installing packages, this might take a couple of minutes.
Installing choo@next, choo-log, choo-devtools, choo-service-worker, and tachyons…
Installing bankai@next, and standard…

Aborting installation. The following error occured:
  npm install --save-dev --cache-min Infinity --loglevel error bankai@next standard

Deleting generated file… package.json
Deleting generated file… node_modules
Cleanup completed, please try again sometime.
```

# Versions
- node: 6.11.0
- npx: 9.6.0

Note. I didn't run `npm -g create-choo-app` I assume npx handles that part.

**Comment by ungoldman** [comment]
I ran `npx create-choo-app new-site` without encountering errors with the following setup:

- macOS 10.12.1
- node v8.2.1
- npx v9.2.1
- npm 5.3.0

I tried with your version of node too and didn't get an error either:

```
~/dev/lab/choo-debug $ node -v
v6.11.2
~/dev/lab/choo-debug $ npm -v
3.10.10
~/dev/lab/choo-debug $ npx -v
9.6.0
```

For now I'm unable to reproduce the error you reported. Please let us know if it persists!

**Comment by mcdonnelldean** [comment]
@ungoldman Thanks for checking. I ran it again and it seemed to work fine. Judging by the error I wonder if I simply got a timeout which killed the whole thing. Nevertheless, it worked! yay
