### ISSUE TITLE
Test script isn't working

### ISSUE THREAD

**Issue by HoverBaum** [choojs/create-choo-app#22]
When using `create-choo-app` and running `npm test` right after creating a project I first get some standard errors and complains that

> 'test-deps' is not recognized as an internal or external command, operable program or batch file.

It seems to me it might be worth updating the test script to something similar like choojs/choo uses.
We could add `dependency-check` to our package and use that to test the input file. Turning the test script into:

```
"test": "standard && dependency-check package.json && dependency-check --unused --no-dev package.json",
```

I am running on Windows 10 if that makes any difference :)

**Comment by yoshuawuyts** [comment]
Yeah, we should be using that. Probably include a `--ignore tachyons` as it
only ever exposes CSS. A PR for this would be really helpful, thanks! :D

**Comment by HoverBaum** [comment]
Maybe this is rather an issue with something not being published right?

The scripts section that gets created for me is:
```
"scripts": {
    "build": "bankai build index.js",
    "inspect": "bankai inspect index.js",
    "start": "bankai start index.js",
    "test": "standard && test-deps",
    "test-deps": "dependency-check . && dependency-check . --extra --no-dev -i tachyons"
  },
```

While here I see it should create:
```
"scripts": {
      "build": "bankai build index.js",
      "inspect": "bankai inspect index.js",
      "start": "bankai start index.js",
      "test": "standard && npm run test-deps",
      "test-deps": "dependency-check . && dependency-check . --extra --no-dev -i tachyons"
    }
```

That might fix my troubles. 

On the same note I see a lot of `\n`s around for the standard files which would fix standard complaining about missing new lines.

I have `v1.6.1` installed and package.json on GitHub says that is the current version but somehow the published code seems to be different.

**Comment by ungoldman** [comment]
re:

> On the same note I see a lot of \ns around for the standard files which would fix standard complaining about missing new lines.

we could also lazily run `standard --fix` after install 🙃

**Comment by yoshuawuyts** [comment]
@ungoldman lol sure yeah why not, would just be an extra step in index.js,
added to the end of bin.js - PR? :D

**Comment by HoverBaum** [comment]
@ungoldman on the other hand that is really lazy and we might as well just provide code in the style we suggest to follow ^^

For that we could add things as their own files here and have those checked against the standard ;)

@yoshuawuyts  I am unsure what is needed here as I feel the version I got from npm is not what is currently in the repo and some concerns might have already been addressed.

**Comment by YerkoPalma** [comment]
test script is working now

```txt
> tmp@1.0.0 test /home/ubuntu/workspace/tmp
> standard && npm run test-deps


> tmp@1.0.0 test-deps /home/ubuntu/workspace/tmp
> dependency-check . && dependency-check . --extra --no-dev -i tachyons

Success! All dependencies used in the code are listed in package.json
Success! All dependencies in package.json are used in the code
```

thanks
