### ISSUE TITLE
[windows] Error creating new project

### ISSUE THREAD

**Issue by Amanpreet24** [choojs/create-choo-app#3]
Hello,
Thank You for creating this tool!

I am trying to create choo-app using this cli on windows. However, it errors out.

`> node -v `
 v8.1.2
`> npm -v`
 v5.3.0
`> npx -v`
 v9.2.0

Globally installed
`> create-choo-app --version`
![capture1](https://user-images.githubusercontent.com/21136419/28494031-b382dbe6-6ef0-11e7-93a4-6b733fb895a4.PNG)

`> create-choo-app monster`
![capture](https://user-images.githubusercontent.com/21136419/28494051-f5d48634-6ef0-11e7-89d6-e83cd16547d3.PNG)

**Comment by yoshuawuyts** [comment]
Should be all fixed! :D
