### ISSUE TITLE
npm install old cached pkg

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/create-choo-app#30]
My choo version is 5.6.2 in my npm cached list, so npm installs choo@5.6.2, it causes [#19](https://github.com/choojs/create-choo-app/issues/19)

I modified the statement in `exports.install`:

`var cmd = 'npm install --save --cache-min Infinity --loglevel error ' + packages` to
`var cmd = 'npm install --save --cache-min 0 --loglevel error ' + packages`

Failed, npm still installs choo@5.6.2

So, how about cleaning cache before install, something like this:
```javascript
var cmd = 'npm cache clean choo && npm install --save --loglevel error ' + packages
```
It works.

**Comment by yoshuawuyts** [comment]
This is a tricky one — perhaps we should remove `-cache-min Infinity`, and we should be good. That way it always checks, and we can still install offline. Would that work for you?

**Comment by ZhouHansen** [comment]
No, it doesn't work, neither add --prefer-online. See this issue : Disabling
cache completely <https://github.com/npm/npm/issues/11338>

2017-10-20 23:57 GMT+08:00 Yoshua Wuyts <notifications@github.com>:

**Comment by goto-bus-stop** [comment]
should be fixed in https://github.com/choojs/create-choo-app/pull/50; thanks!
