### ISSUE TITLE
Access static files

### ISSUE THREAD

**Issue by g-a-v-i-n** [choojs/create-choo-app#33]
I can't seem to find an example of loading fonts, images, markdown etc as statically served files. For example, react-create-app automatically serves all static assets from a folder called 'public'. Can anyone point me to resources about how to do this?

**Comment by yoshuawuyts** [comment]
Heya, apologies for the lack of documentation. We automatically pick up on any directories named `assets/` or `content/` — we should probably add `public/` too. Hope this answers your question!

**Comment by g-a-v-i-n** [comment]
Thanks for the clarification. Really liking Choo!

**Comment by yoshuawuyts** [comment]
Yay, glad you like it! Closing this issue for the moment; let us know if you run into anything else! C:
