### ISSUE TITLE
Certificate warnings on new app start devserver

### ISSUE THREAD

**Issue by nkanderson** [choojs/create-choo-app#38]
On creating a new app and running `npm start`, I'm forced to confirm a security exception on any browser where I pull up `localhost:8080` (specifically, Firefox 57, Chrome 62, Safari 11). From comments on [bankai issue #307](https://github.com/choojs/bankai/issues/307#issuecomment-340522190), it sounds like that may be expected behavior.

Can you confirm that the expected workaround is to confirm the localhost URL security exception on all browsers? If so, it may be worth adding to the README, as it's a bit unexpected to spin up a new project and hit warnings right away.

**Comment by yoshuawuyts** [comment]
Hey! - yeah, this is expected behavior. We should definitely add a note on this in the docs, you're right!

**Comment by nkanderson** [comment]
Awesome, thanks! Those PRs look super helpful. Documentation with screenshots is 💯

Do you think it's worth adding the location of the generated Bankai certs (`~/.config/bankai/`) under the "How does this work" section?
