### ISSUE TITLE
'npm start' fails with 'SyntaxError: Assigning to rvalue'

### ISSUE THREAD

**Issue by chrisdwheatley** [choojs/create-choo-app#48]
Hallo 👋, I'm seeing the error `SyntaxError: Assigning to rvalue` when creating a new app with `create-choo-app`.

Environment;

* macOS Sierra 10.12.16
* node 8.9.4
* npm 5.6.0
* npx 9.7.1

Commands;

* `npx create-choo-app choo-example`
* `cd choo-example`
* `npm start`

Error;

```
(node:96280) ExperimentalWarning: The http2 module is an experimental API.
scripts:browserify.bundle Assigning to rvalue (3:45)
SyntaxError: Assigning to rvalue (3:45)
    at Parser.pp$4.raise (/projects/choo-example/node_modules/acorn/dist/acorn.js:2684:13)
    at Parser.pp$2.toAssignable (/projects/choo-example/node_modules/acorn/dist/acorn.js:1581:12)
    at Parser.pp$3.parseMaybeAssign (/projects/choo-example/node_modules/acorn/dist/acorn.js:1885:47)
    at Parser.pp$3.parseExpression (/projects/choo-example/node_modules/acorn/dist/acorn.js:1851:19)
    at Parser.pp$1.parseStatement (/projects/choo-example/node_modules/acorn/dist/acorn.js:809:45)
    at Parser.pp$1.parseTopLevel (/projects/choo-example/node_modules/acorn/dist/acorn.js:700:23)
    at Parser.parse (/projects/choo-example/node_modules/acorn/dist/acorn.js:545:15)
    at parse (/projects/choo-example/node_modules/acorn/dist/acorn.js:3741:37)
    at module.exports (/projects/choo-example/node_modules/falafel/index.js:22:15)
    at /projects/choo-example/node_modules/static-module/index.js:30:13
```

**Comment by chrisdwheatley** [comment]
A quick search suggests it could be an issue with the code being compiled somewhere, see https://github.com/vuejs/vue-template-es2015-compiler/issues/8.

**Comment by chrisdwheatley** [comment]
`npm run build` errors too, it looks like the same issue;

```
➜ choo-example git:(master) npm run build

> choo-example@1.0.0 build /projects/choo-example
> bankai build index.js

13:21:52 ✨  Compiling & compressing files

13:21:52 ✨  created: dist
13:21:52 ✨  created: dist/manifest.json
13:21:52 ✨  created: dist/assets/icon.png
13:21:52 ✨  created: dist/manifest.json.gz
13:21:52 ✨  created: dist/manifest.json.deflate
13:21:52 ✨  created: dist/manifest.json.br
13:21:54 🚨  scripts:browserify.bundle {"pos":60,"loc":{"line":3,"column":45},"raisedAt":80}
```

**Comment by chrisdwheatley** [comment]
I tried replicating this on a different machine and I'm seeing what seems to be a similar issue but with different output.

I did notice that the version of `choo` installed is pretty outdated, here's my `package.json` when running the same commands as in the original issue, this time on the following versions.

* macOS El Capitan 10.11.3
* node 9.2.0
* npm 5.5.1
* npx 9.6.0

package.json
```
{
  "name": "choo-example-2",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "bankai build index.js",
    "create": "choo-scaffold",
    "inspect": "bankai inspect index.js",
    "start": "bankai start index.js",
    "test": "standard && npm run test-deps",
    "test-deps": "dependency-check . && dependency-check . --extra --no-dev -i tachyons"
  },
  "dependencies": {
    "choo": "^5.6.2",
    "choo-service-worker": "^2.1.5",
    "sheetify": "^6.1.0",
    "tachyons": "^4.7.4"
  },
  "devDependencies": {
    "bankai": "^8.1.1",
    "choo-devtools": "^1.3.1",
    "choo-scaffold": "^1.1.2",
    "dependency-check": "^3.0.0",
    "standard": "^10.0.2"
  }
}
```

I'm struggling to figure out why this'd be happening, would be interested to see if anyone else can replicate.

**Comment by goto-bus-stop** [comment]
I think this might be because we do

```
npm install --save --cache-min Infinity
```

without specifying version ranges for dependencies. So it installs the latest version that you have cached locally. If you do `npm install choo@6` somewhere else and then run create-choo-app again, it will probably get the new version 🤔 

It would be good if you would always get the newest version with create-choo-app, though! maybe we should drop the --cache-min part for now?

**Comment by chrisdwheatley** [comment]
Thanks for the help @goto-bus-stop, that does look to be the issue.

Because I've previously installed versions of a lot of the dependencies it looks like a few of them were out of date, rather than updating each I ran `npm cache clean --force`.

It looks like this has caused issues previously and @yoshuawuyts [suggested removing the `--cache-min` flag](https://github.com/choojs/create-choo-app/issues/30#issuecomment-338247961), I'm going to submit a PR to do that.

**Comment by yoshuawuyts** [comment]
@chrisdwheatley PR merged! Hopefully that will resolve all issues going forward :grin:

**Comment by chrisdwheatley** [comment]
Thanks @yoshuawuyts 👍!
