### ISSUE TITLE
encountered  error while using npm start

### ISSUE THREAD

**Issue by ookangzheng** [choojs/create-choo-app#52]
<img width="1180" alt="screen shot 2018-02-14 at 9 36 40 am" src="https://user-images.githubusercontent.com/6301735/36183736-aabc4cfa-116a-11e8-832c-ce636192efdd.png">

**Comment by chrisdwheatley** [comment]
Thanks for reporting the error @ookangzheng.

I'm seeing the same issue and have [reported it](https://github.com/choojs/bankai/issues/424) in the underlying library that `create-choo-app` is using for compilation, bankai.

As a temporary workaround to get you back up and running you can amend the version of bankai in your `package.json` to `9.5.0` and reinstall your node modules. This should avoid the issue which seems to have appeared in `9.6.0`.

**Comment by goto-bus-stop** [comment]
`npm update` should give you bankai@9.6.1 which fixes this. thanks!

**Comment by ookangzheng** [comment]
yap, thanks a lot
