### ISSUE TITLE
"Unexpected token function"

### ISSUE THREAD

**Issue by ynx0** [choojs/create-choo-app#55]
When I try to use it, the command errors out.
```
$ npx create-choo-app baithakcom
npx: installed 61 in 9.265s
C:\Users\lux\AppData\Roaming\npm-cache\_npx\17116\node_modules\create-choo-app\bin.js
Unexpected token function
```

**Comment by yoshuawuyts** [comment]
@ynx0 oh sorry about that! - what's your node version? I believe there might be an `async` function in the tree somewhere, so either node 8 or 9 is required. Thanks!

**Comment by markphd** [comment]
@ynx0 it worked! 👍

**Comment by goto-bus-stop** [comment]
@yoshuawuyts should we add an `engines` key to package.json so that pre Node 8 will log a warning?

**Comment by yoshuawuyts** [comment]
@goto-bus-stop sounds good!

**Comment by ynx0** [comment]
Whoops, my bad :stuck_out_tongue:
