### ISSUE TITLE
Got error while npm start at fresh package

### ISSUE THREAD

**Issue by ookangzheng** [choojs/create-choo-app#62]
<img width="1126" alt="screen shot 2018-05-16 at 06 04 54" src="https://user-images.githubusercontent.com/6301735/40086046-48dbeb06-58cf-11e8-8ba7-8e83fc0df48e.png">

**Comment by goto-bus-stop** [comment]
The on-performance module does not work in Node 10 yet; a patch landed but I can't publish a new version yet until the module ownership is transfered to the choo org.

You can work around it by commenting out choo-devtools until then:

```js
// app.use(require('choo-devtools')())
```

**Comment by goto-bus-stop** [comment]
Fixed in :package: on-performance 1.2.2
