### ISSUE TITLE
Tell users how to start their app

### ISSUE THREAD

**Issue by timwis** [choojs/create-choo-app#8]
I think the other common generators say something like "use `npm start` to run your app" - might be helpful for users less familiar with npm scripts?

**Comment by yoshuawuyts** [comment]
@timwis good point; think we can improve this. Fwiw here's some prior art:

<img width="1280" alt="screen shot 2017-07-23 at 19 08 32" src="https://user-images.githubusercontent.com/2467194/28501591-416529ca-6fdf-11e7-9714-f1a45a6aee0c.png">

<img width="1280" alt="screen shot 2017-07-23 at 19 56 09" src="https://user-images.githubusercontent.com/2467194/28501676-03c9bfc0-6fe1-11e7-9c61-4623e91b2583.png">
